name: Release docker image
on:
  push:
  pull_request:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        base-image: [ubuntu:22.04, ubuntu:24.04]
        qt-version: [6.5.3, 6.4.2]

    steps:
      - uses: actions/checkout@v4
      # 仅非 PR 场景才登录 GHCR
      - name: Login to GHCR
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo REPO_SLUG="${repo,,}" >> ${GITHUB_ENV}
        env:
          repo: ${{ github.repository}}

      - run: echo IMAGE_URI="ghcr.io/${{ env.REPO_SLUG }}" >> ${GITHUB_ENV}

      - name: Extract Ubuntu version
        run: |
          UBUNTU_VERSION=$(echo "${{ matrix.base-image }}" | cut -d':' -f2)
          echo "UBUNTU_VERSION=${UBUNTU_VERSION}" >> ${GITHUB_ENV}
          echo "IMAGE_FULL_NAME=${{ env.IMAGE_URI }}:qt-${{ matrix.qt-version }}-${UBUNTU_VERSION}" >> ${GITHUB_ENV}

      - name: Build cpp_tools base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cpp_tools.Dockerfile
          push: true
          load: true
          build-args: |
            BASE_IMAGE=${{ matrix.base-image }}
          tags: |
            ${{ env.IMAGE_URI }}:cpp_tools-${{ env.UBUNTU_VERSION }}

      - name: Build qt image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./qt.Dockerfile
          push: false # should push after next step success
          load: true
          build-args: |
            BASE_IMAGE=${{ env.IMAGE_URI }}:cpp_tools-${{ env.UBUNTU_VERSION }}
            QT_VERSION=${{ matrix.qt-version }}
          tags: |
            ${{ env.IMAGE_FULL_NAME }}


      - name:  Smoke Test build a tiny Qt project
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.IMAGE_FULL_NAME }}
          run: |
            git clone https://github.com/euler0/mini-cmake-qt.git
            cd mini-cmake-qt
            git reset --hard 39d568a05318bec619f470942a18980968df22c3
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
            cmake --build build

      - name: Push qt image
        if: ${{ github.event_name == 'push' }}
        run: |
          docker push "${{ env.IMAGE_FULL_NAME }}"
